{% set name = "nox-poetry" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nox_poetry-{{ version }}.tar.gz
  sha256: 2531a404e3a21eb73fc1a587a548506a8e2c4c1e6e7ef0c1d0d8d6453b7e5d26

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - nox >=2020.8.22
    - tomlkit >=0.7
    - packaging >=20.9

test:
  imports:
    - nox_poetry
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cjolowicz/nox-poetry
  summary: nox-poetry
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - renan-r-santos
